Vidly/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vidly.Models;

namespace Vidly.Controllers
{
    public class CustomerController : Controller
    {
        // GET: Customer
        public ActionResult Index()
        {
            List<Customer> customerList = new List<Customer>() {
                new Customer() { Id=1,
                Name="Jose"
                },
                new Customer() {Id=2, Name="Fatima" }

            };

            customerList.Add(new Customer() { Id = 3, Name = "Esmeralda" });
            return View("Index", customerList);
        }

        public ActionResult Details(int id)
        {
            List<Customer> customerList = new List<Customer>() {
                new Customer() { Id=1,
                Name="Jose"
                },
                new Customer() {Id=2, Name="Fatima" }

            };

            customerList.Add(new Customer() { Id = 3, Name = "Esmeralda" });
            var customer = customerList.FirstOrDefault(x => x.Id == id);
            if (customer == null)
            {
                return HttpNotFound();
            }

            //var customer = from cust in customerList
            //               where cust.Id == id
            //               select cust;



            return View("Details", customer);
        }
    }
}

Vidly/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @Html.Partial("_NavBar")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Vidly/Views/Shared/_NavBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Vidly", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Customers", "Index", "Customer")</li>
                <li>@Html.ActionLink("Movies", "About", "Home")</li>
                
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>